name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg ENTERPRISES_DB_URL="${{ secrets.ENTERPRISES_DB_URL }}" \
            --build-arg ULLER_DB_URL="${{ secrets.ULLER_DB_URL }}" \
            --build-arg ULLER_DB_NAME="${{ secrets.ULLER_DB_NAME }}" \
            -t bethecozmo/saas-backend:latest --push .

      - name: Deploy to Swarm
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          sudo apt-get install -y sshpass
          # Realiza a conexão SSH usando sshpass e senha
          sshpass -p "$DEPLOY_PASSWORD" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
            # Garante que o Swarm está ativo (se não estiver, o pipeline falha)
            docker info --format '{{.Swarm.LocalNodeState}}' | grep -q "active" || exit 1

            # Verifica se o serviço 'saas-backend' já existe
            docker service ls | grep -q saas-backend
            if [ $? -eq 0 ]; then
              # Se o serviço existir, faz o update da imagem
              docker service update --image bethecozmo/saas-backend:latest saas-backend
            else
              # Se o serviço não existir, cria o serviço
              docker service create --name saas-backend -p 8080:8080 bethecozmo/saas-backend:latest
            fi
          EOF